description: >
  Site Web dédié à la tenue de compte des tirages moitié-moitié de l'équipe
  marketing de Spectra Premium.
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
title: Tirage moitié-moitié